/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface MyFooter {
    }
    interface MyHeader {
    }
    interface MyLike {
        "isLiked": boolean;
        "onToggleLike": Function;
    }
    interface MySideDrawer {
        "open": () => Promise<void>;
        "opened": boolean;
        "title": string;
    }
    interface MySpinner {
    }
    interface MyStockFinder {
    }
    interface MyStockprice {
        "stockSymbol": string;
    }
}
export interface MyStockFinderCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMyStockFinderElement;
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLMyFooterElement extends Components.MyFooter, HTMLStencilElement {
    }
    var HTMLMyFooterElement: {
        prototype: HTMLMyFooterElement;
        new (): HTMLMyFooterElement;
    };
    interface HTMLMyHeaderElement extends Components.MyHeader, HTMLStencilElement {
    }
    var HTMLMyHeaderElement: {
        prototype: HTMLMyHeaderElement;
        new (): HTMLMyHeaderElement;
    };
    interface HTMLMyLikeElement extends Components.MyLike, HTMLStencilElement {
    }
    var HTMLMyLikeElement: {
        prototype: HTMLMyLikeElement;
        new (): HTMLMyLikeElement;
    };
    interface HTMLMySideDrawerElement extends Components.MySideDrawer, HTMLStencilElement {
    }
    var HTMLMySideDrawerElement: {
        prototype: HTMLMySideDrawerElement;
        new (): HTMLMySideDrawerElement;
    };
    interface HTMLMySpinnerElement extends Components.MySpinner, HTMLStencilElement {
    }
    var HTMLMySpinnerElement: {
        prototype: HTMLMySpinnerElement;
        new (): HTMLMySpinnerElement;
    };
    interface HTMLMyStockFinderElementEventMap {
        "mysymbolSelected": string;
    }
    interface HTMLMyStockFinderElement extends Components.MyStockFinder, HTMLStencilElement {
        addEventListener<K extends keyof HTMLMyStockFinderElementEventMap>(type: K, listener: (this: HTMLMyStockFinderElement, ev: MyStockFinderCustomEvent<HTMLMyStockFinderElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLMyStockFinderElementEventMap>(type: K, listener: (this: HTMLMyStockFinderElement, ev: MyStockFinderCustomEvent<HTMLMyStockFinderElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLMyStockFinderElement: {
        prototype: HTMLMyStockFinderElement;
        new (): HTMLMyStockFinderElement;
    };
    interface HTMLMyStockpriceElement extends Components.MyStockprice, HTMLStencilElement {
    }
    var HTMLMyStockpriceElement: {
        prototype: HTMLMyStockpriceElement;
        new (): HTMLMyStockpriceElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "my-footer": HTMLMyFooterElement;
        "my-header": HTMLMyHeaderElement;
        "my-like": HTMLMyLikeElement;
        "my-side-drawer": HTMLMySideDrawerElement;
        "my-spinner": HTMLMySpinnerElement;
        "my-stock-finder": HTMLMyStockFinderElement;
        "my-stockprice": HTMLMyStockpriceElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface MyFooter {
    }
    interface MyHeader {
    }
    interface MyLike {
        "isLiked"?: boolean;
        "onToggleLike"?: Function;
    }
    interface MySideDrawer {
        "opened"?: boolean;
        "title"?: string;
    }
    interface MySpinner {
    }
    interface MyStockFinder {
        "onMysymbolSelected"?: (event: MyStockFinderCustomEvent<string>) => void;
    }
    interface MyStockprice {
        "stockSymbol"?: string;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "my-footer": MyFooter;
        "my-header": MyHeader;
        "my-like": MyLike;
        "my-side-drawer": MySideDrawer;
        "my-spinner": MySpinner;
        "my-stock-finder": MyStockFinder;
        "my-stockprice": MyStockprice;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "my-footer": LocalJSX.MyFooter & JSXBase.HTMLAttributes<HTMLMyFooterElement>;
            "my-header": LocalJSX.MyHeader & JSXBase.HTMLAttributes<HTMLMyHeaderElement>;
            "my-like": LocalJSX.MyLike & JSXBase.HTMLAttributes<HTMLMyLikeElement>;
            "my-side-drawer": LocalJSX.MySideDrawer & JSXBase.HTMLAttributes<HTMLMySideDrawerElement>;
            "my-spinner": LocalJSX.MySpinner & JSXBase.HTMLAttributes<HTMLMySpinnerElement>;
            "my-stock-finder": LocalJSX.MyStockFinder & JSXBase.HTMLAttributes<HTMLMyStockFinderElement>;
            "my-stockprice": LocalJSX.MyStockprice & JSXBase.HTMLAttributes<HTMLMyStockpriceElement>;
        }
    }
}
